import Head from "next/head";
import Image from "next/image";
import { useGetGoodsQuery } from "../app/utils/store/goodsApi";
import s from "../app/styles/Home.module.scss";

import Card from "../app/components/Card";
import { NextPage } from "next";
import CartDropdown from "../app/components/Cart";
import { useTypedSelector } from "../app/utils/hooks/useTypedSelector";
import { useState } from "react";

const Home: NextPage = () => {
  const [count, setCount] = useState(10);
  const { isLoading, data: goods } = useGetGoodsQuery(count);
  console.log(goods);
  isLoading && <p>Loading...</p>;
  const { cart } = useTypedSelector((state) => state.cart);
  const getTotalQuantity = () => {
    let total = 0;
    cart.forEach((item) => {
      total += item.quantity;
    });
    return total;
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CartDropdown />
      <p>{cart.length}</p>
      <main className={s.cards}>
        {goods?.map((g) => (
          <Card
            key={g.id}
            image={g.image}
            title={g.title}
            category={g.category}
            price={g.price}
            rating={g.rating}
            quantity={g.quantity}
          />
        ))}
      </main>
      <div className={s.bottom}>
        <button className={s.buttonLoadMore} onClick={() => setCount(prev => prev + 5)}>Загрузить ещё</button>
      </div>
    </>
  );
};

export default Home;
